# Generated by Django 2.2.5 on 2019-12-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='portada',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
    ]
