# Generated by Django 2.2.6 on 2019-10-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Tipo_album', models.CharField(max_length=30)),
                ('Fecha_lanzamiento', models.DateField(auto_now=True)),
                ('Duracion_album', models.TimeField()),
                ('Estrellas', models.IntegerField()),
                ('Imagen', models.ImageField(upload_to='pic_folder/')),
            ],
        ),
        migrations.CreateModel(
            name='Cantante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Nombre_artistico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_realizacion', models.DateField(auto_now=True)),
                ('Concepto', models.TextField(blank=True)),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Nombre_artistico', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=60)),
                ('Estrellas', models.IntegerField()),
                ('Fecha_lanzamiento', models.DateField(auto_now=True)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Duracion_album', models.TimeField()),
                ('Imagen', models.ImageField(upload_to='pic_folder/')),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Album')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=128)),
                ('Correo', models.EmailField(max_length=254, unique=True)),
                ('Estado', models.BooleanField(default=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cliente')),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Rol')),
            ],
        ),
        migrations.CreateModel(
            name='Tema_Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Productor')),
                ('Tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Tema_Cantante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cantante')),
                ('Tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_realizacion', models.DateField(auto_now=True)),
                ('Cantidad', models.PositiveIntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Album')),
                ('Compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Compra')),
                ('Tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Tema')),
            ],
        ),
        migrations.CreateModel(
            name='Album_Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Album')),
                ('Genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Genero')),
            ],
        ),
    ]
