# Generated by Django 2.2.5 on 2019-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20191207_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='caratula',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='cantante',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='cantante',
            name='portada',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='portada',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
    ]
