# Generated by Django 2.2.5 on 2019-12-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20191207_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='sonido',
            field=models.FileField(blank=True, upload_to='musica/'),
        ),
    ]
