# Generated by Django 2.2.5 on 2019-12-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_cancion_sonido'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='caratula',
            field=models.ImageField(blank=True, upload_to='pic_folder/'),
        ),
    ]
